name: Frontend CI

on:
  push:
    branches: [ main, develop ]
  pull request:
    branches: [ main ]

jobs:
  lint-test-build-frontend:
    name: Lint, Test & Build Frontend
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./frontend # Set working directory untuk frontend

    strategy:
      matrix:
        node-version: [18.x, 20.x] 
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json # Path ke package-lock.json

    - name: Install frontend dependencies
      run: npm ci # Menggunakan npm ci lebih disarankan di CI

    - name: Run frontend linter
      run: npm run lint

    - name: Check frontend formatting
      run: npm run format:check # Mengaktifkan kembali check formatting

    - name: Run frontend tests with coverage
      run: npm run test:ci # Skrip yang menjalankan Jest dengan cakupan